#!/bin/bash

# Creates a dump of the given database's schema only
# (not it's data) in a 'data' folder in the current 
# directory. Name can be specified as an argument; 
# otherwise default to 'schema.dump'

filename=schema
if [[ $1 != "" ]]; then
    filename=$1 
fi

filename=data/${filename}.dump

# Can use "heroku pg:credentials:url --app [app-name]" to
# get the database name, host, port, username, and password
# for the given app. In future, consider adding a .pgpass 
# file to do this automatically 

echo -n "dbname > " 
read dbname

echo -n "host > "
read host

echo -n "port > "
read port

echo -n "username > "
read username

# Make directory /data if it doesn't exist
mkdir --parents data

pg_dump --dbname=$dbname --host=$host --port=$port --username=$username --file=$filename --verbose --clean --no-owner --schema-only --no-privileges --if-exists

echo "done"
exit 0