#!/bin/bash

# Loads a local development database
# with the credentials below

if [[ $1 == "" ]]; then
	echo "provide path to dump file"
	exit 1
fi

# For local databases:
#   host = localhost
#   port = 5432
#   username = postgres

echo -n "dbname > " 
read dbname

echo -n "host > "
read host

echo -n "port > "
read port

echo -n "username > "
read username

echo -e "Loading database with schema from $1 \n\n"

psql --dbname=$dbname --file=$1 --echo-all --echo-errors --host=$host --port=$port --username=$username

echo "done"
exit 0